language: ruby
rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
gemfile:
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_4_1.gemfile
matrix:
  exclude:
    - rvm: 2.3.8
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: 2.4.6
      gemfile: gemfiles/rails_4_1.gemfile
    - rvm: 2.4.6
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: 2.5.5
      gemfile: gemfiles/rails_4_1.gemfile
    - rvm: 2.6.3
      gemfile: gemfiles/rails_4_1.gemfile
before_install: gem update bundler
sudo: false
